repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 3db014c16a9d31997ab8c07a4d61fcce936c8f0d  # v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          - feat
          - fix
          - docs
          - style
          - refactor
          - perf
          - test
          - build
          - ci
          - chore
          - revert
